apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 1  # Reduza para 1 réplicas para economizar recursos
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-app
        image: <seu-usuario-docker>/<nome-da-imagem>:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"  # Define um uso mínimo de 512MB de memória
            cpu: "250m"      # Requisita 25% de 1 vCPU
          limits:
            memory: "768Mi"  # Limita o uso de memória a 768MB
            cpu: "500m"      # Limita o uso de CPU a 50% de 1 vCPU
---
apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
spec:
  type: LoadBalancer  # Pode ser alterado para NodePort ou ClusterIP dependendo da sua necessidade
  selector:
    app: meu-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
